app:
  server:
    shutdown_timeout: 10s

    http:
      origin: "http://localhost:8008"
      host: "0.0.0.0"
      port: "8008"
      read_timeout: 10s
      write_timeout: 20s
      allowed_origins: ["http://localhost:8008", "www.livechatpaxy.ru", "livechatpaxy.ru"]

    ws:
      host: "0.0.0.0"
      port: "8009"
      read_timeout: 15s
      write_timeout: 30s
      read_buffer_size: 1024
      write_buffer_size: 1024
      read_limit: 1024
      read_deadline: 60s
      ping_interval: 5s

  db:
    migration_path: "file://migrations/"
    healthcheck_interval: 5s
    connection_timeout: 5s

  telegram:
    exp_in: 8h
